version: '3'

services:
  postgres:
    container_name: delo_db
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sdb
    volumes:
      - ./docker/data-postgres:/var/lib/postgresql/data
    ports:
      - "5444:5432"