"""add timestamp

Revision ID: 0005
Revises: 0004
Create Date: 2024-06-01 09:17:33.183757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('consultations', sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('referrals', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('referrals', sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('uq_referrer', 'referrals', type_='unique')
    op.add_column('users', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_updated')
    op.drop_column('users', 'date_created')
    op.create_unique_constraint('uq_referrer', 'referrals', ['added', 'adding'])
    op.drop_column('referrals', 'date_updated')
    op.drop_column('referrals', 'date_created')
    op.drop_column('consultations', 'date_updated')
    op.drop_column('consultations', 'date_created')
    # ### end Alembic commands ###
